version: "3"

volumes:
  node_modules:

services:
  app:
    container_name: engineer-sns-client
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
